import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/global/SessionWrapper";
import { ThemeProvider } from "@/components/global/theme-provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Algorhythm",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionWrapper>
            <html>
                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <main className="w-screen bg-[#fff] text-white flex justify-end">
                            {children}
                        </main>
                        <Toaster />
                    </ThemeProvider>
                </body>
            </html>
        </SessionWrapper>
    );
}
