WORD_BANK = {
    "energy": {
        0: [
            "Motionless",
            "Static",
            "Still",
            "Dormant",
            "Inactive",
            "Lifeless",
            "Silent",
            "Flat",
            "Idle",
            "Immobile",
            "Unmoving",
            "absent",
            "devoid",
        ],
        1: [
            "Faint",
            "Subdued",
            "Whispery",
            "Gentle",
            "Calm",
            "Soft",
            "Quiet",
            "Hushed",
            "Tranquil",
            "Dim",
            "Minimal",
            "Featherlight",
        ],
        2: [
            "Light",
            "Mild",
            "Delicate",
            "Low-key",
            "Modest",
            "Mellow",
            "Unhurried",
            "Subtle",
            "Reticent",
            "Smooth",
            "Relaxed",
        ],
        3: [
            "Mildly active",
            "Gentle",
            "Lightly dynamic",
            "Softly vibrant",
            "Low-intensity",
            "Unassertive",
            "Leisurely",
            "Languid",
            "Unobtrusive",
            "Slightly lively",
        ],
        4: [
            "Easygoing",
            "Unagitated",
            "Relaxed",
            "Restrained",
            "Even",
            "Mid-paced",
            "Tempered",
            "Smooth",
            "Unhurried",
            "Unruffled",
        ],
        5: [
            "Balanced",
            "Moderate",
            "Even-tempered",
            "Steady",
            "Measured",
            "Temperate",
            "Controlled",
            "Neutral",
            "Consistent",
            "Intermediate",
            "Regular",
            "Reasonable",
        ],
        6: [
            "Refreshed",
            "Brisk",
            "Buoyant",
            "Upbeat",
            "Middling",
            "Active",
            "Motivated",
            "Stimulated",
            "Perky",
            "Peppy",
            "Harmonious",
        ],
        7: [
            "Exhilarated",
            "Energized",
            "Vibrant",
            "Dynamic",
            "Spirited",
            "Engaging",
            "Animated",
            "Exciting",
            "Up-tempo",
            "Effervescent",
        ],
        8: [
            "Thrilling",
            "Forceful",
            "Kinetic",
            "Robust",
            "Lively",
            "Pulsing",
            "Exuberant",
            "Electric",
            "Vibrant",
            "Invigorated",
        ],
        9: [
            "Intense",
            "Vigorous",
            "Radiant",
            "High-octane",
            "Exhilarating",
            "High-velocity",
            "Pulsating",
            "Overpowering",
            "Turbocharged",
        ],
        10: [
            "Raucous",
            "Blazing",
            "Boisterous",
            "Frenzied",
            "Hyper-energetic",
            "Supercharged",
            "Explosive",
            "Ferocious",
            "Unstoppable",
            "Frenetic",
            "Uncontainable",
            "Thunderous",
        ],
    },
    "danceability": {
        0: [
            "Static",
            "Immobile",
            "Stationary",
            "Unmoving",
            "Sedentary",
            "Still",
            "Rigid",
            "Stagnant",
            "Lifeless",
            "Inert",
        ],
        1: [
            "Barely-animated",
            "Sluggish",
            "Drowsy",
            "Lethargic",
            "Feeble",
            "Slow-paced",
            "Subdued",
            "Plodding",
            "Dull",
            "Listless",
        ],
        2: [
            "Uneventful",
            "Monotonous",
            "Bland",
            "Tepid",
            "Indifferent",
            "Lazy",
            "Low-energy",
            "Underwhelming",
            "Dreary",
            "Flat",
        ],
        3: [
            "Mild",
            "Gentle",
            "Soft",
            "Restrained",
            "Easygoing",
            "Light",
            "Modest",
            "Unhurried",
            "Tranquil",
            "Mild-mannered",
        ],
        4: [
            "Steady",
            "Controlled",
            "Moderate",
            "Smooth",
            "Balanced",
            "Easy",
            "Calm",
            "Unpretentious",
            "Casual",
            "Relaxed",
        ],
        5: [
            "Rhythmic",
            "Mid-tempo",
            "Even",
            "Consistent",
            "Moderate-paced",
            "Mellow",
            "Groove",
            "Laid-back",
            "Unruffled",
        ],
        6: [
            "Upbeat",
            "Lively",
            "Engaging",
            "Energetic",
            "Perky",
            "Spirited",
            "Animated",
            "Peppy",
            "Buoyant",
            "Invigorating",
        ],
        7: [
            "Vibrant",
            "Bouncy",
            "Playful",
            "Brisk",
            "Enthusiastic",
            "Zesty",
            "Dynamic",
            "Uplifting",
        ],
        8: [
            "Fast-paced",
            "High-energy",
            "Exciting",
            "Electrifying",
            "Jumping",
            "Kinetic",
            "Stimulating",
            "Eager",
            "Effervescent",
        ],
        9: [
            "Frenzied",
            "Hyper",
            "Exhilarating",
            "Pulsating",
            "Vigorous",
            "Fiery",
            "High-spirited",
            "Jubilant",
        ],
        10: [
            "Explosive",
            "Intense",
            "Feverish",
            "Wild",
            "Unstoppable",
            "Hypnotic",
            "Ecstatic",
            "Mesmerizing",
            "Thrilling",
            "Heart-pounding",
        ],
    },
    "acousticness": {
        0: [
            "Synthetic",
            "Electronic",
            "Artificial",
            "Digitized",
            "Processed",
            "Mechanical",
            "Robotic",
            "High-tech",
            "Programmed",
            "Industrial",
        ],
        1: [
            "Techno-driven",
            "Digitally-enhanced",
            "Computerized",
            "Electrified",
            "Engineered",
            "Futuristic",
            "Augmented",
            "Virtual",
            "Cybernetic",
        ],
        2: [
            "Electronically-modified",
            "Synthesized",
            "Man-made",
            "Electroacoustic",
            "Studio-crafted",
            "Synthetic-fused",
            "High-fidelity",
            "Digitally-altered",
            "Process-intensive",
            "Synth-focused",
        ],
        3: [
            "Semi-electronic",
            "Partly-synthetic",
            "Hybridized",
            "Electro-mechanical",
            "Engineered-textures",
            "Sound-designed",
            "Technologically-blended",
            "Mechanically-enhanced",
            "Electro-infused",
            "Digitally-tinged",
        ],
        4: [
            "Electronically-touched",
            "Processed-sound",
            "Digitally-mixed",
            "Electro-acoustic",
            "Synthetic-tinged",
            "Sound-shaped",
            "Moderately-processed",
            "Engineered",
            "Tech-influenced",
            "Subtly-electronic",
        ],
        5: [
            "Balanced",
            "Mixed",
            "Fusion",
            "Moderately-acoustic",
            "Equalized",
            "Blend",
            "Hybrid",
            "Partly-organic",
            "Synthetic-organic",
            "Mixed-textures",
        ],
        6: [
            "Mildly-acoustic",
            "Lightly-processed",
            "Acoustic-leaning",
            "Organic-synthetic",
            "Acoustic-enhanced",
            "Sound-blended",
            "Semi-natural",
            "Acoustic-touched",
            "Lightly-synthetic",
            "Natural-processed",
        ],
        7: [
            "Warm",
            "Natural-sounding",
            "Organic-tinged",
            "Unprocessed",
            "Acoustic-textured",
            "Raw-feeling",
            "Gently-produced",
            "Organic-blended",
        ],
        8: [
            "Acoustic-driven",
            "Earthy-tones",
            "Pure-sounding",
            "Natural-vibe",
            "Raw-sounding",
            "Unrefined",
            "Organic-heavy",
            "Unadulterated",
            "Authentic",
            "Genuine",
        ],
        9: [
            "Bare",
            "Unembellished",
            "Simple",
            "Acoustic-rich",
            "Raw",
            "Unmodified",
            "Clean",
            "Natural",
            "Unfiltered",
        ],
        10: [
            "Raw",
            "Organic",
            "Unprocessed",
            "Unplugged",
            "Natural",
            "Pure",
            "Genuine",
            "Real",
            "Earthy",
            "Authentic",
        ],
    },
}

KEY_TRAITS_PROMPT = "You are tasked with describing how a given tag [A] describes a given song, using its musical features [B] and lyrics [C]. The same way that this paragraph is written for the word upbeat, write another paragraph in the same style and length that describes any word the user provides. Be sure to vary the sentence structure, syntax, but maintain the tone and keep it as short if not shorter than this example. It is important that your output is roughly the same length as the output below. Only include the paragraph, not the word itself or any additional formatting or information.\nUpbeat:\nSignifies a bold and energetic atmosphere, capturing the essence of confident flair and lively, spirited moments. This tag implies catchy rhythms, vibrant melodies, and possibly playful elements that evoke the charm and attitude of sass. You must not include the user-provided word in your response. Only output the paragraph and not any additional information or formatting. The paragraph must not exceed three sentences in length."
